# Generated by Django 2.2.1 on 2019-05-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworksdb',
            name='image',
            field=models.ImageField(upload_to='UploadImage'),
        ),
    ]
