# Generated by Django 2.2.1 on 2019-05-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20190524_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworksdb',
            name='image',
            field=models.ImageField(upload_to='UploadedImages'),
        ),
    ]
